# экран
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 650
SCREEN_TITLE = "PyJourney"

# физика
GRAVITY = 0.5
PLAYER_JUMP_SPEED = 12
PLAYER_MOVEMENT_SPEED = 5

# скейлинг
SPRITE_SCALING = 0.5
TILE_SCALING = 0.5
COIN_SCALING = 0.5

# обновление анимки
UPDATES_PER_FRAME = 7